/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	F:/ARMChina/project/SD_HDMI_DAFENQI/TD/al_ip/PLL.v
 ** Date	:	2024 05 16
 ** TD version	:	5.6.71036
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000MHz
//	Clock multiplication factor: 3
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 150.000000MHZ	| 0  DEG     
//		C1        	| 150.000000MHZ	| 270DEG     
//		C3        	| 100.000000MHZ	| 0  DEG     
//		C4        	| 100.000000MHZ	| 180DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module PLL (
  refclk,
  reset,
  extlock,
  clk0_out,
  clk1_out,
  clk3_out,
  clk4_out 
);

  input refclk;
  input reset;
  output extlock;
  output clk0_out;
  output clk1_out;
  output clk3_out;
  output clk4_out;

  wire clk0_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC0_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(4),
    .ICP_CURRENT(13),
    .KVCO(4),
    .LPF_CAPACITOR(1),
    .LPF_RESISTOR(4),
    .REFCLK_DIV(1),
    .FBCLK_DIV(3),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(6),
    .CLKC0_CPHASE(5),
    .CLKC0_FPHASE(0),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(6),
    .CLKC1_CPHASE(3),
    .CLKC1_FPHASE(4),
    .CLKC3_ENABLE("ENABLE"),
    .CLKC3_DIV(9),
    .CLKC3_CPHASE(8),
    .CLKC3_FPHASE(0),
    .CLKC4_ENABLE("ENABLE"),
    .CLKC4_DIV(9),
    .CLKC4_CPHASE(3),
    .CLKC4_FPHASE(4) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(extlock),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({open, open, open, open, open, open, open, open}),
    .fbclk(clk0_out),
    .clkc({clk4_out, clk3_out, open, clk1_out, clk0_buf}) 
  );

endmodule

